begin;

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  normalized_term text not null
    check (char_length(normalized_term) between 2 and 40),
  created_at timestamptz not null default now()
);

create index if not exists search_events_created_at_idx
  on public.search_events(created_at desc);
create index if not exists search_events_term_created_idx
  on public.search_events(normalized_term, created_at desc);
create index if not exists search_events_user_term_created_idx
  on public.search_events(user_id, normalized_term, created_at desc);

alter table public.search_events enable row level security;

-- 검색 기록은 브라우저에서 직접 읽거나 쓰지 않고 백엔드에서만 처리합니다.
revoke all on public.search_events from anon, authenticated;
grant all privileges on public.search_events to service_role;
grant usage, select on sequence public.search_events_id_seq to service_role;

commit;
