begin;

create table if not exists public.recommended_search_terms (
  id bigint generated by default as identity primary key,
  term text not null unique
    check (char_length(term) between 2 and 40),
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recommended_search_terms_active_order_idx
  on public.recommended_search_terms(is_active, sort_order, created_at);

alter table public.recommended_search_terms enable row level security;
revoke all on public.recommended_search_terms from anon, authenticated;
grant all privileges on public.recommended_search_terms to service_role;
grant usage, select on sequence public.recommended_search_terms_id_seq to service_role;

commit;
