begin;

create table if not exists public.user_consents (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'kakao_sync',
  terms_version text not null,
  privacy_version text not null,
  terms_agreed boolean not null default false,
  privacy_agreed boolean not null default false,
  consent_details jsonb not null default '[]'::jsonb,
  agreed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (user_id, terms_version, privacy_version)
);

create index if not exists user_consents_user_agreed_idx
  on public.user_consents(user_id, agreed_at desc);

alter table public.user_consents enable row level security;

revoke all on public.user_consents from anon, authenticated;
grant all privileges on public.user_consents to service_role;
grant usage, select on sequence public.user_consents_id_seq to service_role;

commit;
